# Generated by Django 5.2.5 on 2025-09-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('scores', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='nam_hoc',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scores.namhoc'),
        ),
        migrations.AddField(
            model_name='phanconggiangday',
            name='giao_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phan_congs', to='teachers.giaovien'),
        ),
        migrations.AddField(
            model_name='phanconggiangday',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phan_congs', to='classes.lophoc'),
        ),
        migrations.AddField(
            model_name='phanconggiangday',
            name='mon_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phan_congs', to='subjects.monhoc'),
        ),
        migrations.AddField(
            model_name='phanconggiangday',
            name='nam_hoc',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phan_congs', to='scores.namhoc'),
        ),
        migrations.AlterUniqueTogether(
            name='phanconggiangday',
            unique_together={('lop', 'giao_vien', 'mon_hoc', 'nam_hoc')},
        ),
    ]
