# Generated by Django 5.2.5 on 2025-09-03 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TietHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu', models.IntegerField(choices=[(2, 'Thứ 2'), (3, 'Thứ 3'), (4, 'Thứ 4'), (5, 'Thứ 5'), (6, 'Thứ 6'), (7, 'Thứ 7')])),
                ('tiet', models.IntegerField()),
                ('phan_cong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiet_hoc', to='classes.phanconggiangday')),
            ],
            options={
                'unique_together': {('phan_cong', 'thu', 'tiet')},
            },
        ),
    ]
