# Generated by Django 5.2.5 on 2025-09-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_tiethoc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tiethoc',
            unique_together=set(),
        ),
    ]
