# Generated by Django 5.2.5 on 2025-09-13 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thongbao',
            name='nguoi_nhan',
        ),
        migrations.AddField(
            model_name='thongbao',
            name='email_phu_huynh',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='thongbao',
            name='hoc_sinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.hocsinh'),
        ),
    ]
