# Generated by Django 5.2.5 on 2025-09-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_thongbao_nguoi_nhan_thongbao_email_phu_huynh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thongbao',
            old_name='ngay_tao',
            new_name='ngay_gui',
        ),
        migrations.RemoveField(
            model_name='thongbao',
            name='email_phu_huynh',
        ),
        migrations.RemoveField(
            model_name='thongbao',
            name='hoc_sinh',
        ),
        migrations.RemoveField(
            model_name='thongbao',
            name='nguoi_gui',
        ),
    ]
