# Generated by Django 5.2.5 on 2025-09-02 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HocSinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nu', 'Nữ'), ('Khac', 'Khác')], default='Nam', max_length=10)),
                ('email_phu_huynh', models.EmailField(blank=True, max_length=254, null=True)),
                ('lop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoc_sinhs', to='classes.lophoc')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ho_ten'],
            },
        ),
    ]
