# Generated by Django 5.2.5 on 2025-09-02 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HocKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hoc_ky', models.IntegerField(choices=[(1, 'Học kỳ 1'), (2, 'Học kỳ 2')])),
            ],
        ),
        migrations.CreateModel(
            name='NamHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nam', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_diem', models.CharField(choices=[('mieng', 'Điểm miệng'), ('15p', 'Điểm 15 phút'), ('gk', 'Giữa kỳ'), ('ck', 'Cuối kỳ')], max_length=10)),
                ('diem_so', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('ngay_nhap', models.DateTimeField(auto_now_add=True)),
                ('hoc_sinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_diem', to='students.hocsinh')),
                ('mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_diem', to='subjects.monhoc')),
                ('hoc_ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_diem', to='scores.hocky')),
                ('nam_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_diem', to='scores.namhoc')),
            ],
        ),
    ]
