# Generated by Django 5.2.5 on 2025-09-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiemDanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('trang_thai', models.CharField(choices=[('co mat', 'Co mat'), ('vang', 'Vang'), ('tre', 'Tre')], default='co mat', max_length=10)),
            ],
        ),
    ]
