# Generated by Django 5.2.5 on 2025-09-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemdanh',
            name='hoc_sinh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.hocsinh'),
        ),
        migrations.AlterUniqueTogether(
            name='diemdanh',
            unique_together={('hoc_sinh', 'ngay')},
        ),
    ]
