# Generated by Django 5.2.5 on 2025-09-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diemdanh',
            name='trang_thai',
            field=models.CharField(choices=[('C', 'Co mat'), ('V', 'Vang'), ('M', 'Tre')], default='co mat', max_length=10),
        ),
    ]
