# Generated by Django 5.2.5 on 2025-09-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_mon', models.CharField(max_length=20, unique=True)),
                ('ten_mon', models.CharField(max_length=100)),
            ],
        ),
    ]
